<a href="https://colab.research.google.com/github/yethu-KL29/NLP-Extractive_Summarisation/blob/main/NLP_Extractive_Text_Summarisation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import nltk
nltk.download('punkt') # one time execution
import re

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [2]:
df = pd.read_csv("/content/tennis_articles.csv" , encoding='iso-8859-1')


In [3]:
df.head()

article_id                                      article_title  \
0           1  I do not have friends in tennis, says Maria Sh...   
1           2  Federer defeats Medvedev to advance to 14th Sw...   
2           3  Tennis: Roger Federer ignored deadline set by ...   
3           4  Nishikori to face off against Anderson in Vien...   
4           5  Roger Federer has made this huge change to ten...   

                                        article_text  \
0  Maria Sharapova has basically no friends as te...   
1  BASEL, Switzerland (AP) — Roger Federer advanc...   
2  Roger Federer has revealed that organisers of ...   
3  Kei Nishikori will try to end his long losing ...   
4  Federer, 37, first broke through on tour over ...   

                                              source  
0  https://www.tennisworldusa.org/tennis/news/Mar...  
1  http://www.tennis.com/pro-game/2018/10/copil-s...  
2  https://scroll.in/field/899938/tennis-roger-fe...  
3  http://www.tennis.com/pro-game/2018/10/nishiko...  
4  https://www.express.co.uk/sport/tennis/1036101...

In [4]:
df['article_text'][0]


"Maria Sharapova has basically no friends as tennis players on the WTA Tour. The Russian player has no problems in openly speaking about it and in a recent interview she said: 'I don't really hide any feelings too much. I think everyone knows this is my job here. When I'm on the courts or when I'm on the court playing, I'm a competitor and I want to beat every single person whether they're in the locker room or across the net. So I'm not the one to strike up a conversation about the weather and know that in the next few minutes I have to go and try to win a tennis match. I'm a pretty competitive girl. I say my hellos, but I'm not sending any players flowers as well. Uhm, I'm not really friendly or close to many players. I have not a lot of friends away from the courts.' When she said she is not really close to a lot of players, is that something strategic that she is doing? Is it different on the men's tour than the women's tour? 'No, not at all. I think just because you're in the same

In [5]:
from nltk.tokenize import sent_tokenize
# Download the punkt package if you haven't already
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [6]:
sent_tokenize(df['article_text'][0])

['Maria Sharapova has basically no friends as tennis players on the WTA Tour.',
 "The Russian player has no problems in openly speaking about it and in a recent interview she said: 'I don't really hide any feelings too much.",
 'I think everyone knows this is my job here.',
 "When I'm on the courts or when I'm on the court playing, I'm a competitor and I want to beat every single person whether they're in the locker room or across the net.",
 "So I'm not the one to strike up a conversation about the weather and know that in the next few minutes I have to go and try to win a tennis match.",
 "I'm a pretty competitive girl.",
 "I say my hellos, but I'm not sending any players flowers as well.",
 "Uhm, I'm not really friendly or close to many players.",
 "I have not a lot of friends away from the courts.'",
 'When she said she is not really close to a lot of players, is that something strategic that she is doing?',
 "Is it different on the men's tour than the women's tour?",
 "'No, not at

In [7]:
sentences = []
for s in df['article_text']:
  sentences.append(sent_tokenize(s))

In [8]:
sentences = [y for x in sentences for y in x]


In [9]:
print(sentences)

['Maria Sharapova has basically no friends as tennis players on the WTA Tour.', "The Russian player has no problems in openly speaking about it and in a recent interview she said: 'I don't really hide any feelings too much.", 'I think everyone knows this is my job here.', "When I'm on the courts or when I'm on the court playing, I'm a competitor and I want to beat every single person whether they're in the locker room or across the net.", "So I'm not the one to strike up a conversation about the weather and know that in the next few minutes I have to go and try to win a tennis match.", "I'm a pretty competitive girl.", "I say my hellos, but I'm not sending any players flowers as well.", "Uhm, I'm not really friendly or close to many players.", "I have not a lot of friends away from the courts.'", 'When she said she is not really close to a lot of players, is that something strategic that she is doing?', "Is it different on the men's tour than the women's tour?", "'No, not at all.", "I 

In [10]:
clean_sentences = pd.Series(sentences).str.replace("[^a-zA-Z]", " ")


In [11]:
clean_sentences = [s.lower() for s in clean_sentences]
clean_sentences

['maria sharapova has basically no friends as tennis players on the wta tour.',
 "the russian player has no problems in openly speaking about it and in a recent interview she said: 'i don't really hide any feelings too much.",
 'i think everyone knows this is my job here.',
 "when i'm on the courts or when i'm on the court playing, i'm a competitor and i want to beat every single person whether they're in the locker room or across the net.",
 "so i'm not the one to strike up a conversation about the weather and know that in the next few minutes i have to go and try to win a tennis match.",
 "i'm a pretty competitive girl.",
 "i say my hellos, but i'm not sending any players flowers as well.",
 "uhm, i'm not really friendly or close to many players.",
 "i have not a lot of friends away from the courts.'",
 'when she said she is not really close to a lot of players, is that something strategic that she is doing?',
 "is it different on the men's tour than the women's tour?",
 "'no, not at

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
# Initialize the TF-IDF Vectorizer with stop words
tfidf_vectorizer = TfidfVectorizer(stop_words='english')

# Fit and transform the text data
vector_sentence = tfidf_vectorizer.fit_transform(sentences)

In [19]:
# Convert the sparse matrix to a dense matrix (optional)
dense_matrix = vector_sentence.toarray()

# Display the TF-IDF matrix
print(dense_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [20]:
from sklearn.metrics.pairwise import cosine_similarity

# Compute cosine similarity between all sentence pairs
cosine_sim_matrix = cosine_similarity(dense_matrix)

# Display the similarity matrix
print(cosine_sim_matrix)


[[1.         0.         0.         ... 0.04134813 0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.04134813 0.         0.         ... 1.         0.06450157 0.        ]
 [0.         0.         0.         ... 0.06450157 1.         0.11199104]
 [0.         0.         0.         ... 0.         0.11199104 1.        ]]


In [21]:
# Here, we select the sentences with the highest cosine similarity scores to the first sentence
summary_indices = np.argsort(cosine_sim_matrix[0])[-2:]  # Top 2 sentences

# Print the summary
summary = [sentences[i] for i in summary_indices]
print("Extractive Summary:", summary)


Extractive Summary: ['ALSO READ: Maria Sharapova reveals how tennis keeps her motivated.', 'Maria Sharapova has basically no friends as tennis players on the WTA Tour.']
